services:
  - type: web
    name: gestionale-agenti
    env: python
    region: frankfurt # Low latency in Europe / Italy
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: DRIVE_FOLDER_URL
        value: https://drive.google.com/drive/folders/1IpEMQjuEiRjJ19bpvjo8Ql7qH_Qcnl0Y
      - key: APP_PIN
        value: "1234" # Cambia questo PIN a tuo piacimento
